spring.application.name=demo


spring.datasource.url=jdbc:h2:mem:taskflow
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=va


spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true


spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.h2.console.settings.web-allow-others=true

spring.jpa.defer-datasource-initialization=true

server.error.include-message=always
server.error.include-exception=true
server.error.include-stacktrace=always

# Stripe
stripe.api.key=${STRIPE_API_KEY}
